### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by SethTisue** [jvican/sbt-release-early#36]
this came up on scala/center Gitter (https://gitter.im/scala/center?at=5e42254d19597421f3bfe517)

before archiving, I'd suggest linking to sbt-ci-release from the readme

**Comment by jvican** [comment]
I replied to the feedback in https://gitter.im/scala/center?at=5e43dd90cd2d737bb0724ec7, sbt-release-early now lives in jvican/sbt-release-early. Thanks for opening the ticket @SethTisue

**Comment by SethTisue** [comment]
Good solution, thanks.
